trigger:
  none

pool:
  name: 'Default'

variables:
  - group: rjtrailvariable
  - name: azureServiceConnection    
    value: 'rjsercon'
  - name: resourceGroupName
    value: 'rjtrailrg'
  - name: vnetTemplate
    value: 'infra/vnet.bicep'
  - name: vmTemplate
    value: 'infra/vm.bicep'

stages:
- stage: DeployInfrastructure
  displayName: 'Deploy VNet and VM using Bicep'
  jobs:
  - job: DeployResources
    displayName: 'Run Bicep deployments'
    steps:

    - task: AzureCLI@2
      displayName: 'Create Resource Group'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Creating resource group in location: $location"
          az group create \
            --name $(resourceGroupName) \
            --location $location
      env:
        location: $(location)

    - task: AzureCLI@2
      displayName: 'Deploy VNet'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file $(vnetTemplate) \
            --parameters location=$location
      env:
        location: $(location)
      enabled: FALSE

    - task: AzureCLI@2
      name: GetSubnetId
      displayName: 'Get Subnet ID'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          subnetId=$(az network vnet subnet show \
            --resource-group $(resourceGroupName) \
            --vnet-name rjVnet \
            --name rjSubnet \
            --query id -o tsv)
          
          echo "##vso[task.setvariable variable=subnetId;issecret=true]$subnetId"
      env:
        location: $(location)
      enabled: FALSE

    - task: AzureCLI@2
      displayName: 'Deploy Linux VM (Ubuntu)'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file $(vmTemplate) \
            --parameters \
              location=$location \
              adminUsername=$adminUsername \
              adminPassword=$adminPassword \
              subnetId=$(subnetId)
      env:
        location: $(location)
        adminUsername: $(adminUsername)
        adminPassword: $(adminPassword)