trigger:
  none

pool:
  name: 'Default'

variables:
  pythonVersion: '3.10'
  azureWebAppName: 'rjwebapp'

stages:
# ----------- BUILD STAGE -----------
- stage: Build
  displayName: 'Build Stage'
  jobs:
    - job: BuildJob
      displayName: 'Build Job'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(pythonVersion)'
            addToPath: true

        - script: |
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r source/requirements.txt
          displayName: 'Install Dependencies'

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)'
            artifact: 'source-code'
            publishLocation: 'pipeline'
          displayName: 'Publish Source Code'

# ----------- TEST STAGE -----------
- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
    - job: TestJob
      displayName: 'Run Unit Tests'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(pythonVersion)'
            addToPath: true

        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: 'source-code'
            path: '$(Pipeline.Workspace)/source'

        - script: |
            cd $(Pipeline.Workspace)/source
            python -m venv venv
            source venv/bin/activate
            pip install -r source/requirements.txt
            pytest source/tests/test_app.py
          displayName: 'Run Pytest'

# ----------- DEPLOY STAGE -----------
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  condition: succeeded()
  jobs:
    - job: DeployWeb
      displayName: 'Deploy to Azure App Service'
      steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: 'source-code'
            path: '$(Pipeline.Workspace)/source'

#        - script: |
#            sudo apt-get update
#            sudo apt-get install -y zip
#          displayName: 'Install zip (if needed)'

        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Pipeline.Workspace)/source'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
            replaceExistingArchive: true
          displayName: 'Package Application'

        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'rjsercon'
            appType: 'webApp'
            appName: '$(azureWebAppName)'
            package: '$(Build.ArtifactStagingDirectory)/app.zip'
          displayName: 'Deploy to Azure App Service'
